#define ENABLE_MODULE_SERIAL_ENHANCED

#include "StepperSlave.h"

#define SLAVE_ADDR X_AXIS

#define CLK_PIN 10
#define CW_PIN 11
#define RX_PIN 8
#define TX_PIN 9
#define SENSOR_PIN 6
#define INDICATOR_PIN 13

#if (SLAVE_ADDR == X_AXIS) || (SLAVE_ADDR == Y_AXIS) || (SLAVE_ADDR == G_AXIS)
#define EN_PIN NOT_CONNECTED
#define BRAKE_PIN NOT_CONNECTED
#define INVERT_BRAKE HIGH_LOGIC_BRAKE
#define INVERT_ENABLE HIGH_LOGIC_BRAKE
#define BRAKE_RELEASE_DELAY NO_DELAY
#define BRAKE_ENGAGE_DELAY NO_DELAY
#elif (SLAVE_ADDR == T_AXIS)
#define EN_PIN 12
#define BRAKE_PIN 7
#define INVERT_BRAKE HIGH_LOGIC_BRAKE
#define INVERT_ENABLE LOW_LOGIC_ENABLE
#define BRAKE_RELEASE_DELAY 250
#define BRAKE_ENGAGE_DELAY 1500
#elif (SLAVE_ADDR == Z_AXIS)
#define EN_PIN NOT_CONNECTED
#define BRAKE_PIN NOT_CONNECTED
#define INVERT_BRAKE HIGH_LOGIC_BRAKE
#define INVERT_ENABLE LOW_LOGIC_ENABLE
#define BRAKE_RELEASE_DELAY NO_DELAY
#define BRAKE_ENGAGE_DELAY NO_DELAY
#endif

StepperSlave slave(
  SLAVE_ADDR,
  RX_PIN, TX_PIN,
  CLK_PIN, CW_PIN,
  EN_PIN,
  SENSOR_PIN,
  BRAKE_PIN,
  INVERT_BRAKE,
  INDICATOR_PIN,
  INVERT_ENABLE,
  BRAKE_RELEASE_DELAY,
  BRAKE_ENGAGE_DELAY);

void setup() {
  slave.begin();
#if (SLAVE_ADDR == X_AXIS) || (SLAVE_ADDR == Y_AXIS) || (SLAVE_ADDR == G_AXIS)
  pinMode(12, OUTPUT);
  digitalWrite(12, LOW);
#endif
}

void loop() {
  slave.update();
}