#ifndef CONFIG_H
#define CONFIG_H

#define DEVELOPMENT_MODE 1

#define RX_PIN 16
#define TX_PIN 17
#define LED_GREEN_PIN 2
#define LED_YELLOW_PIN 4
#define LED_RED_PIN 5

#define SYNC_SET_PIN 25
#define SYNC_WAIT_PIN 27
#define DETECT_PIN 26

#if DEVELOPMENT_MODE == 1
#define USE_STA_MODE
#define WIFI_SSID "silenceAndSleep"
#define WIFI_PASSWORD "11111111"
#else
#define USE_AP_MODE
#define WIFI_SSID "Palletizer_Control"
#define WIFI_PASSWORD "palletizer2025"
#endif

#define UART_BAUD_RATE 9600
#define SERIAL_BAUD_RATE 115200

#define MEMORY_CHECK_INTERVAL 10000
#define SYSTEM_CHECK_INTERVAL 5000
#define WIFI_CHECK_INTERVAL 30000

#define MIN_FREE_HEAP 10000
#define CRITICAL_HEAP_THRESHOLD 5000
#define MIN_LARGEST_BLOCK 4096

#define MAX_LOG_BUFFER_SIZE 2000
#define SYNC_TIMEOUT_MS 30000

#define WATCHDOG_TIMEOUT_SEC 30

#define HTTP_TASK_STACK_SIZE 8192
#define UART_TASK_STACK_SIZE 4096
#define SYSTEM_TASK_STACK_SIZE 2048

#define HTTP_TASK_PRIORITY 2
#define UART_TASK_PRIORITY 3
#define SYSTEM_TASK_PRIORITY 1

#define HTTP_TASK_CORE 0
#define UART_TASK_CORE 1
#define SYSTEM_TASK_CORE 0

#endif